package com.mycompany.quedeahuevooficial;

import com.menuitem.ActualizarProducto;
import com.menuitem.BorrarProducto;
import com.menuitem.CrearProducto;
import com.menuitem.ListaProductos;
import com.miusuarios.ActualizarUsuario;
import com.miusuarios.BorrarUsuarios;
import com.miusuarios.ListaUsuarios;
import com.miventa.Venta;
import java.awt.Dimension;
import javax.swing.JDesktopPane;

/**
 *
 * @author aries
 */
public class Menu extends javax.swing.JFrame {
    public static JDesktopPane DesktopPane_menu;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        this.setSize(new Dimension(1200, 700));
        this.setExtendedState(Menu.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.setTitle("Sistema de Ventas");
        
        this.setLayout(null);
        DesktopPane_menu = new JDesktopPane();
        
        int ancho = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        int alto = java.awt.Toolkit.getDefaultToolkit().getScreenSize().width;
        Menu.DesktopPane_menu.setBounds(0, 0,ancho, (alto -110));
        this.add(DesktopPane_menu);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        miCrearProducto = new javax.swing.JMenuItem();
        miActualizarPro = new javax.swing.JMenuItem();
        miBorrarPro = new javax.swing.JMenuItem();
        miLista = new javax.swing.JMenuItem();
        jmanuitem = new javax.swing.JMenu();
        miListaUsuarios = new javax.swing.JMenuItem();
        miCrearUsuario = new javax.swing.JMenuItem();
        miBorrarUsuario = new javax.swing.JMenuItem();
        miActualizarUsuario = new javax.swing.JMenuItem();
        venta = new javax.swing.JMenu();
        miVenta = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Producto");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        miCrearProducto.setText("Crear un Producto");
        miCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCrearProductoActionPerformed(evt);
            }
        });
        jMenu1.add(miCrearProducto);

        miActualizarPro.setText("Actualizar");
        miActualizarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miActualizarProActionPerformed(evt);
            }
        });
        jMenu1.add(miActualizarPro);

        miBorrarPro.setText("Borrar");
        miBorrarPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBorrarProActionPerformed(evt);
            }
        });
        jMenu1.add(miBorrarPro);

        miLista.setText("Listar");
        miLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListaActionPerformed(evt);
            }
        });
        jMenu1.add(miLista);

        jMenuBar1.add(jMenu1);

        jmanuitem.setText("Usuario");

        miListaUsuarios.setText("Lista de Usuarios");
        miListaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miListaUsuariosActionPerformed(evt);
            }
        });
        jmanuitem.add(miListaUsuarios);

        miCrearUsuario.setText("Crear Usuario");
        miCrearUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCrearUsuarioActionPerformed(evt);
            }
        });
        jmanuitem.add(miCrearUsuario);

        miBorrarUsuario.setText("Borrar Usuario");
        miBorrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miBorrarUsuarioActionPerformed(evt);
            }
        });
        jmanuitem.add(miBorrarUsuario);

        miActualizarUsuario.setText("Actualizar Usuario");
        miActualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miActualizarUsuarioActionPerformed(evt);
            }
        });
        jmanuitem.add(miActualizarUsuario);

        jMenuBar1.add(jmanuitem);

        venta.setText("Venta");

        miVenta.setText("Venta");
        miVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miVentaActionPerformed(evt);
            }
        });
        venta.add(miVenta);

        jMenuBar1.add(venta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 677, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCrearProductoActionPerformed
        CrearProducto crearproducto = new CrearProducto();
        DesktopPane_menu.add(crearproducto);
        crearproducto.setVisible(true);
    }//GEN-LAST:event_miCrearProductoActionPerformed

    private void miActualizarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miActualizarProActionPerformed
        ActualizarProducto actualizarproducto = new ActualizarProducto();
        DesktopPane_menu.add(actualizarproducto);
        actualizarproducto.setVisible(true);
    }//GEN-LAST:event_miActualizarProActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
       
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void miListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListaActionPerformed
        ListaProductos listaproductos = new ListaProductos();
        DesktopPane_menu.add(listaproductos);
        listaproductos.setVisible(true);
    }//GEN-LAST:event_miListaActionPerformed

    private void miBorrarProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBorrarProActionPerformed
        BorrarProducto miborrarpro = new BorrarProducto();
        DesktopPane_menu.add(miborrarpro);
        miborrarpro.setVisible(true);
    }//GEN-LAST:event_miBorrarProActionPerformed

    private void miListaUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miListaUsuariosActionPerformed
        ListaUsuarios listausuarios = new ListaUsuarios();
        DesktopPane_menu.add(listausuarios);
        listausuarios.setVisible(true);
    }//GEN-LAST:event_miListaUsuariosActionPerformed

    private void miCrearUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCrearUsuarioActionPerformed
        CrearUsuario crearusuario = new CrearUsuario();
        crearusuario.setVisible(true);
    }//GEN-LAST:event_miCrearUsuarioActionPerformed

    private void miBorrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miBorrarUsuarioActionPerformed
        BorrarUsuarios borrarusuarios = new BorrarUsuarios();
        DesktopPane_menu.add(borrarusuarios);
        borrarusuarios.setVisible(true);
    }//GEN-LAST:event_miBorrarUsuarioActionPerformed

    private void miActualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miActualizarUsuarioActionPerformed
        ActualizarUsuario actualizarusuario = new ActualizarUsuario();
        DesktopPane_menu.add(actualizarusuario);
        actualizarusuario.setVisible(true);
    }//GEN-LAST:event_miActualizarUsuarioActionPerformed

    private void miVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miVentaActionPerformed
        Venta ventav = new Venta();
        DesktopPane_menu.add(ventav);
        ventav.setVisible(true);
    }//GEN-LAST:event_miVentaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenu jmanuitem;
    private javax.swing.JMenuItem miActualizarPro;
    private javax.swing.JMenuItem miActualizarUsuario;
    private javax.swing.JMenuItem miBorrarPro;
    private javax.swing.JMenuItem miBorrarUsuario;
    private javax.swing.JMenuItem miCrearProducto;
    private javax.swing.JMenuItem miCrearUsuario;
    private javax.swing.JMenuItem miLista;
    private javax.swing.JMenuItem miListaUsuarios;
    private javax.swing.JMenuItem miVenta;
    private javax.swing.JMenu venta;
    // End of variables declaration//GEN-END:variables
}
